name: Validate-Commits
on: [push]
jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get-all-issues
        if: ${{ success() }}
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo "ISSUES<<EOF"
            gh issue list -s all -L 100000 --json number --jq ".[].number"
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: get-pending-commits
        if: ${{ success() }}
        run: |
          {
            echo "COMMITS<<EOF"
            git rev-list ${{ github.event.before }}^..HEAD
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: validate-messages
        if: ${{ success() }}
        run: |
          echo "Commits: $COMMITS"
          while IFS="" read -r commit
          do
            echo "$commit"
          done < $COMMITS