name: Validate-Commits
on: [push]
jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: get-all-issues
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo "ISSUES<<EOF"
            gh issue list -s all -L 100000
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: get-pending-commits
        if: ${{ success() }}
        uses: actions/checkout@v4
        run: |
          {
            echo "COMMITS<<EOF"
            git rev-list ${{ github.event.before }}
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: validate-messages:
        if: ${{ success() }}
        uses: actions/checkout@v4
        run: |
          echo "$ISSUES"
          echo "$COMMITS"