name: Commit-Checker
on: [push, pull_request]
jobs:
  get-all-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "issues=$(gh issue list -s all -L 100000)" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  get-unchecked-commits:
    needs: get-all-issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "commits=$(git rev-list ${{ github.event.before  }}^..HEAD)" >> "$GITHUB_ENV"
  validate-commit-messages:
    needs: get-unchecked-commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "$issues"
          echo "$commits"


