name: Validate-Commits
on: [push]
jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: get-all-issues
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "ISSUES=$(gh issue list -s all -L 100000)" >> "$GITHUB_ENV"
      
      - name: get-pending-commits
        if: ${{ success() }}
        run: |
          git log -n 10
          git rev-list ${{ github.event.before }}^..HEAD
          echo "COMMITS=$(git rev-list ${{ github.event.before }}^..HEAD)" >> "$GITHUB_ENV"
      
      - name: validate-messages
        if: ${{ success() }}
        run: |
          echo "$ISSUES"
          echo "$COMMITS"