name: Validate-Commits
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: run-linter
        if: ${{ success() }}
        run: |
          lintResult=$(./ktlint --reporter=plain-summary | tail -2)
          echo "$lintResult"


  validate-commit-messages:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get-all-issues
        if: ${{ success() }}
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo "ISSUES<<EOF"
            gh issue list -s all -L 100000 --json number --jq ".[].number"
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: get-pending-commits
        if: ${{ success() }}
        run: |
          {
            echo "COMMITS<<EOF"
            git rev-list ${{ github.event.before }}^..HEAD
            echo EOF
          } >> "$GITHUB_ENV"
      
      - name: validate-messages
        if: ${{ success() }}
        run: |
          while IFS="" read -r commit
          do
            issueNum=$(git show -s --format=%B $commit | sed -E -e "s/I//" -e "s/:.*//g")
            if [ $(echo $ISSUES | grep -c "$issueNum") -eq 0 ]; then
              echo "Failure, commit $commit contains no valid issue number in commit message."
              exit 1
            fi
          done <<< "$COMMITS"
    
  format:
    runs-on: ubuntu-latest
    needs: validate-commit-messages
    if: ${{ always() }}
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: run-auto-formatter
        if: ${{ success() }}
        run: |
          ./ktlint -F || true
      
      - name: save-changes
        if: ${{ success() }}
        run: |
          git config user.name DigitagRepoBot
          git config user.email digitagtechteam@gmail.com
          if [ $(git ls-files --modified | wc -l) -gt 0 ]; then
            git commit -am "Autoformat"
            git push
          fi