name: Commit-Checker
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name 'DigitagGitBot'
          git config user.email 'digitagtechteam@gmail.com'
          git config credential.helper cache
          echo "Before SHA: " ${{ github.event.before  }}
          echo "After SHA: " ${{ github.event.after }}
  validateIssue:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh issue list -s all -L 100000
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
