name: Validate-Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: install-jdk
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
        
      - name: install-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: install-android-sdk
        uses: android-actions/setup-android@v3
      
      - name: build
        run: |
          ./gradlew --no-daemon build
      
      - name: run-tests
        run: |
          ./gradlew -d test